Feature/organise tasks
PaulJohannFlade/Capstone_ClanPlan pull request #21
Opened 2024-04-18 17:57 UTC by mariiaovs

2024-04-19 10:29 UTC, Roland-Hufnagel requested changes
Hi team. Great job 💪 so far. Please have a look at my comments. In the UI I cannot find a way to assign a family member to a task. I think this leads to the bug I mentioned in the code review. So please try to improve your code according to my comments.

2024-04-19 10:29 UTC, Roland-Hufnagel commented on components/Modal.js
> +  top: 15%;
to give it 15% is tricky. When the modal appears on top of a long task list, it can be scrolled out of the viewport. Can you find a better solution?

2024-04-19 10:29 UTC, Roland-Hufnagel commented on components/FilterWindow.js
> +    onApply(selectedOptions);
Your onApply seems to have a bug: When I add a new familiy member and after that filter by this new member, the app crashes...

2024-04-19 10:29 UTC, Roland-Hufnagel commented on pages/index.js
> +  );
👍 Love your filter function ❤️

2024-04-22 08:19 UTC, NikRoe approved these changes
LGTM

2024-04-22 08:50 UTC, merged