Feature/assign task to member
PaulJohannFlade/Capstone_ClanPlan pull request #24
Opened 2024-04-22 09:56 UTC by PaulJohannFlade

2024-04-22 13:45 UTC, NikRoe requested changes
Hi there,

nice start!

I left a comment regarding the `assignedTo` key in your objects. In the current state of the application is does not make sense for this to be an array, but it makes more sense to be a string.

The code you write for a feature to implement should only cover what this feature currently needs, not paving the way for features that might come next.
Once you can select multiple persons to assign a task to, it makes sense to change the data type to be an array. But not before that.

Keep it up 🙌

2024-04-23 06:59 UTC, PaulJohannFlade commented on components/TaskDetails.js
> +          {assignedTo.map((id) => (
Thanks for the review! The changes are done. :-)

2024-04-23 07:38 UTC, NikRoe approved these changes
Hi there,

nicely done 🙌 

I left one comment regarding the else-branch in your form's `handleSubmit`. 

Keep it up 👍

2024-04-23 07:38 UTC, NikRoe commented on components/Form.js
> +      onTaskSubmit({ ...data });
This change should not be needed. You are currently passing a new object as the argument and spread `data` to that new object.
In the end, whether the argument is `(data)` or `({ ...data })` it makes no difference in the data type. Both are objects, but going with `({ ...data })` makes the code more complicated than it needs to be.

2024-04-23 13:44 UTC, merged