family creation
PaulJohannFlade/Capstone_ClanPlan pull request #90
Opened 2024-06-03 09:22 UTC by SwethaJanardhana

2024-06-03 12:13 UTC, Jonstar22 commented on components/AuthGate.js
> +`;
You could use `$variant` where the StyledButton is instead of giving it whole new styling :3

2024-06-03 12:35 UTC, Jonstar22 reviewed
Looks good! one little change i would recommend but overall its fine

2024-06-03 12:35 UTC, Jonstar22 commented on pages/api/family/index.js
> +import { authOptions } from "../auth/[...nextauth]";
its better to stay consistent so also use `@/` here instead of `../`

2024-06-03 13:07 UTC, SwethaJanardhana commented on pages/api/family/index.js
> +import { authOptions } from "../auth/[...nextauth]";
thank you...will adapt 👍🏻

2024-06-04 13:18 UTC, niehaus-alexander requested changes
Good work, some suggestions commented.

2024-06-04 13:18 UTC, niehaus-alexander commented on components/Header.js
> +        <StyledSignButton onClick={handleSignIn}>Log in</StyledSignButton>
Same here, if all you do is calling the function you might aswell write it like this:
```js
onClick={( ) => signIn(null, { callbackUrl: "/"})}

2024-06-04 13:18 UTC, niehaus-alexander commented on components/MemberForm.js
> +      <StyledSelect name="role" id="role" onChange={handleRoleChange}>
same here

2024-06-04 14:09 UTC, SwethaJanardhana commented
thank you for your review 👍🏻, for more readability i prefer using a function and define the functionality in there. Please do consider from others perspective 🙂 . 
And regarding the styled components, we'll adapt in next user story styling optimisation

2024-06-04 14:49 UTC, SwethaJanardhana commented
Thanks for the review, implemented changes requested/suggested

2024-06-05 07:29 UTC, niehaus-alexander requested changes
Nice work, still got some suggestions.

2024-06-05 07:29 UTC, niehaus-alexander commented on components/AuthGate.js
> +import FamilyRegisterForm from "./FamilyRegisterForm";
If it is defined in your jsconfig.json, you should consistently use the @ alias in your project.

2024-06-05 07:29 UTC, niehaus-alexander commented on components/AuthGate.js
> +  setShowModal,
I'm not sure if this is new or if I missed it in the first review—if so, I apologize. You should not pass state setter functions directly to components. Instead, create handler functions and pass those, adhering to the appropriate naming conventions such as handleShowModal or onShowModal. This approach enhances readability and maintainability by clearly indicating the purpose of each function.

2024-06-05 07:29 UTC, niehaus-alexander commented on components/FamilyRegisterForm.js
> +import StyledButton from "./StyledButton";
@

2024-06-05 07:29 UTC, niehaus-alexander commented on components/Header.js
> +
If i am not mistaken, this can be removed now.

2024-06-05 07:29 UTC, niehaus-alexander commented on components/AuthGate.js
> +        <Modal $top="7rem" setShowModal={setShowModal} $open={showModal}>
Here and in the app_.js too, revisit your code and write handler functions for your state setter functions to pass as props to the components.

2024-06-05 07:38 UTC, SwethaJanardhana commented on components/AuthGate.js
> +        <Modal $top="7rem" setShowModal={setShowModal} $open={showModal}>
Thanks for the review, we'll implement the requested change in further development story

2024-06-05 10:00 UTC, FelineHuhn approved these changes
Good progress. :) 

As discussed, please change all imports in a separate Fix Branch consitent to “@”, which @niehaus-alexander and @Jonas-Wendland noticed 👍 A developer story for refactoring and removing the passed-through setter functions should also be prioritized (as you already planned I think).

This gives us an insight into how valuable careful reviews are and what can be overlooked over the course of several reviews. 🙏

Keep up the good work 🚀

2024-06-05 10:04 UTC, SwethaJanardhana commented
Thank you so much for the review Feline, will implement the changes requested at top most priority.

2024-06-05 10:21 UTC, merged