Feature/delete image
PaulJohannFlade/Capstone_ClanPlan pull request #95
Opened 2024-06-05 10:09 UTC by mariiaovs

2024-06-05 14:52 UTC, miToe commented on components/StyledButton.js
>    border-bottom: 2px solid var(--color-font);
A little tip for a small optimisation! if you set your border like this: " border: 0.5px solid var(--color-font);
  border-bottom-width: 2px;
" you save yourself the trouble of defining the color and type of border again, which the browser will also find better! ;)

2024-06-05 14:52 UTC, miToe commented on components/MemberProfile.js
> +  left: 61vw;
maybe it's easier to use "right" instead of "left"?

2024-06-05 15:36 UTC, mariiaovs commented on components/MemberProfile.js
Thanks for the idea, implemented.

2024-06-05 15:39 UTC, mariiaovs commented on components/StyledButton.js
>    border-bottom: 2px solid var(--color-font);
Thanks, also implemented.

2024-06-05 15:43 UTC, mariiaovs commented on components/MemberProfile.js
> +  left: 61vw;
You're right, now it's easier. I used "left" because the container didn't have fixed width before. Implemented.

2024-06-06 08:20 UTC, SabinePfanner requested changes
LGTM, just some small comments / suggestions

2024-06-06 08:20 UTC, SabinePfanner commented on components/MemberProfile.js
> +        setShowModal={setShowModal}
If this is a global prop, which is handled the same way in each modal, you could think about handling it globally via an OpenModal and CloseModal function.

2024-06-06 09:58 UTC, mariiaovs commented on components/MemberProfile.js
> +    align-items: start;
In the context of a Flexbox layout, using "start" or "flex-start" with the "align-items" property generally results in the same visual outcome.

2024-06-07 10:43 UTC, mariiaovs commented on components/MemberProfile.js
> +        setShowModal={setShowModal}
now we're using context for this props: showModal, openModal and closeModal functions. Thanks for the idea.

2024-06-10 08:25 UTC, FelineHuhn approved these changes
I only checked the two changes after approving, and lgtm :)

2024-06-10 09:41 UTC, merged